"""
Abstract base class for all trading strategies.
All strategies must inherit from this class to be auto-discovered.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from enum import Enum
import pandas as pd


class Signal(Enum):
    """Trade signal direction."""
    BUY = 1
    SELL = -1
    HOLD = 0


@dataclass
class TradeSignal:
    """Represents a trade signal generated by a strategy."""
    signal: Signal
    symbol: str
    entry_price: float
    stop_loss: float
    take_profit: float
    lot_size: float = 0.01
    comment: str = ""
    magic_number: int = 0

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk/reward ratio."""
        if self.signal == Signal.HOLD:
            return 0.0
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        return reward / risk if risk > 0 else 0.0


@dataclass
class Position:
    """Represents an open trading position."""
    ticket: int
    symbol: str
    type: Signal  # BUY or SELL
    volume: float
    open_price: float
    stop_loss: float
    take_profit: float
    profit: float
    magic_number: int
    comment: str
    open_time: Any


class StrategyBase(ABC):
    """
    Abstract base class for trading strategies.

    To create a new strategy:
    1. Create a new file in strategies/ folder
    2. Inherit from StrategyBase
    3. Implement required methods: initialize, analyze, should_close
    4. Create a YAML config in config/strategies/
    """

    # Strategy metadata - override in subclass
    name: str = "BaseStrategy"
    version: str = "1.0.0"
    description: str = "Base strategy class"
    author: str = "Unknown"

    # Default settings - override in config
    symbols: List[str] = field(default_factory=lambda: ["XAUUSD"])
    timeframe: str = "M15"
    enabled: bool = True

    def __init__(self):
        """Initialize strategy with default values."""
        self.config: Dict[str, Any] = {}
        self.parameters: Dict[str, Any] = {}
        self._initialized: bool = False
        self.symbols = ["XAUUSD"]
        self.timeframe = "M15"
        self.enabled = True

    @abstractmethod
    def initialize(self, config: Dict[str, Any]) -> None:
        """
        Initialize strategy with configuration.
        Called once when strategy is loaded.

        Args:
            config: Strategy configuration from YAML file
        """
        pass

    @abstractmethod
    def analyze(self, symbol: str, data: pd.DataFrame) -> Optional[TradeSignal]:
        """
        Analyze market data and generate trade signal.
        Called on each bar/tick.

        Args:
            symbol: Trading symbol (e.g., "XAUUSD")
            data: OHLCV DataFrame with columns: open, high, low, close, volume, time

        Returns:
            TradeSignal if entry condition met, None otherwise
        """
        pass

    @abstractmethod
    def should_close(self, position: Position, data: pd.DataFrame) -> bool:
        """
        Check if an open position should be closed.

        Args:
            position: Current open position
            data: Current market data

        Returns:
            True if position should be closed, False otherwise
        """
        pass

    def on_tick(self, symbol: str, tick: Dict[str, Any]) -> Optional[TradeSignal]:
        """
        Optional: React to individual ticks for scalping strategies.
        Override this method if you need tick-level execution.

        Args:
            symbol: Trading symbol
            tick: Tick data with bid, ask, time

        Returns:
            TradeSignal if entry condition met, None otherwise
        """
        return None

    def on_trade_opened(self, position: Position) -> None:
        """
        Optional: Called when a trade is opened.
        Override for custom logging or alerts.
        """
        pass

    def on_trade_closed(self, position: Position, profit: float) -> None:
        """
        Optional: Called when a trade is closed.
        Override for custom logging or analytics.
        """
        pass

    def get_trailing_stop(self, position: Position, data: pd.DataFrame) -> Optional[float]:
        """
        Optional: Calculate new stop loss for trailing.
        Override to implement custom trailing stop logic.

        Args:
            position: Current open position
            data: Current market data

        Returns:
            New stop loss price, or None to keep current
        """
        return None

    def _apply_trailing_distance(
        self,
        position: Position,
        current_price: float,
        trail_distance_price: float,
    ) -> Optional[float]:
        """
        Shared helper to convert a trailing distance into a new stop-loss price.

        Args:
            position: Open position
            current_price: Current market price
            trail_distance_price: Absolute distance between market and new SL

        Returns:
            New stop-loss price or None if no valid update
        """
        if trail_distance_price <= 0:
            return None

        if position.type == Signal.BUY:
            new_sl = current_price - trail_distance_price
            if new_sl > position.stop_loss and new_sl < current_price:
                return new_sl
            return None

        # SELL
        new_sl = current_price + trail_distance_price
        if (position.stop_loss == 0 or new_sl < position.stop_loss) and new_sl > current_price:
            return new_sl
        return None

    def validate_config(self, config: Dict[str, Any]) -> bool:
        """
        Validate strategy configuration.
        Override to add custom validation.

        Args:
            config: Configuration to validate

        Returns:
            True if valid, raises ValueError otherwise
        """
        required_keys = ["name", "enabled", "symbols", "timeframe"]
        for key in required_keys:
            if key not in config:
                raise ValueError(f"Missing required config key: {key}")
        return True

    def __str__(self) -> str:
        return f"{self.name} v{self.version}"

    def __repr__(self) -> str:
        return f"<Strategy: {self.name} v{self.version} enabled={self.enabled}>"
